version: "3.7"

services:
    askpdf:
        image: askpdf:dev
        build:
            context: .
            dockerfile: Dockerfile
        user: ${UID:-1000}:${GID:-1000}
        ports:
            - "${APP_PORT:-7000}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        # env_file:
        #     - .env.dev
        environment:
            DB_HOST: host.docker.internal
        volumes:
            - .:/var/www/html
        networks:
            - askpdf
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"


networks:
    askpdf:

