version: "3.7"

services:
    askpdf:
        image: askpdf:latest
        build:
            context: .
            dockerfile: Dockerfile
        # user: ${UID:-1000}:${GID:-1000}
        ports:
            - "${APP_PORT:-80}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        env_file:
            - .env
        environment:
            DB_HOST: host.docker.internal
        volumes:
            - askpdf_data:/var/www/html
        networks:
            - askpdf
        restart: unless-stopped
        extra_hosts:
            - "host.docker.internal:host-gateway"


volumes:
    askpdf_data:

networks:
    askpdf:

