name: Deploy demo

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetching local repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t mrmed/askpdf:latest .

      - name: Push the image to Docker Hub
        run: docker push mrmed/askpdf:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy the demo mode
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            cd ~/core
            # Pull the new image
            docker pull mrmed/askpdf:latest

            # Stop and remove the old demo containers
            docker rm -fv core_askpdf_1 core_askdox_1

            # Up everything
            docker-compose up -d

            # Run migrations
            docker exec core_askpdf_1 php artisan migrate --force -n
            docker exec core_askdox_1 php artisan migrate --force -n

            # Run DB seeds
            docker exec core_askpdf_1 php artisan db:seed --force -n
            docker exec core_askdox_1 php artisan db:seed --force -n


            # Some space clean up
            docker image prune -f

            # Inform me
            curl -H "Authorization: Bearer ${{ secrets.NTFY_TOKEN }}" \
            -H "Title: ✅ AskPDF & AskDox demo successfully deployed." \
            -d "" \
            https://ntfy.mr4web.com/dev
