name: Deploy demo

on:
  workflow_dispatch:
  push:
    tag:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fetching local repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t mrmed/askpdf:latest .

      - name: Push the image to Docker Hub
        run: docker push mrmed/askpdf:latest


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy the demo mode
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASS }}
          port: ${{ secrets.VPS_PORT }}
          script_stop: true
          script: |
            cd ~/core
            docker pull mrmed/askpdf:latest
            docker stop rm -fv core_askpdf_1 core_askdox_1
            docker-compose up -d
            docker image prune -f
